rails/eventz/config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "events" => "events#index"
  get "events/:id" => "events#show", as: "event"
end

rails/eventz/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/eventz/app/models/event.rb
class Event < ApplicationRecord
  def free?
    price.blank? || price.zero?
  end
end

rails/eventz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/eventz/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @age = 100
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end
end

rails/eventz/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/eventz/app/helpers/events_helper.rb
module EventsHelper
  def format_price(price)
    if price == 0
      content_tag(:strong, "Free")
    else
      number_to_currency(price)
    end
  end
end

rails/eventz/app/views/events/index.html.erb
<section>
  <h1><%= pluralize(@events.size, 'Event') %></h1>
  <ol>
    <% @events.each do |event| %>
      <li>
        <p>
          <strong><%= link_to(event.name, "events/#{event.id}") %></strong> in <%= event.location %>. Price: <%= format_price(event.price) %>
       </p>
       <p>
        <strong>When:</strong> <%= event.starts_at =%>
       </p>
        <p><%= truncate(event.description, length: 35, separator: ' ') %></p>
      </li>
    <% end %>
  </ol>
</section>

rails/eventz/app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p><%= @event.location %></p>
<p><%= format_price(@event.price) %></p>
<%= link_to "All Events", events_path %>

rails/eventz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>